prepare:
  test_size: 0.2
  random_state: 42
  min_text_length: 3

features:
  max_tfidf_features: 30000
  ngram_range: [1, 3]
  max_tfidf_char_features: 10000
  char_ngram_range: [3, 4]
  min_df: 2
  max_df: 0.95

train:
  logreg:
    C: 2.0
    max_iter: 2000
    solver: liblinear
    penalty: l2
  linearsvc:
    C: 0.5
    max_iter: 2000
  xgboost:
    n_estimators: 250
    max_depth: 4
    learning_rate: 0.15
    reg_alpha: 0.1
    reg_lambda: 1.0
    subsample: 0.85
    colsample_bytree: 0.85
    min_child_weight: 3
    tree_method: hist